---
title: <span style="color:#88398A">R-Ladies Montevideo 2018 </span>
author: <span style="color:#88398A""> <font size="6">@RLadiesMVD</span></font>


date: <span style="color:#88398A""> 12 de Abril, 2018
output: ioslides_presentation
logo: logo.png
widescreen: no
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## <span style="color:#88398A"> ¿Qué es R-Ladies?</span> 

Es una organización internacional que promueve la diversidad de género en la comunidad de R a través de reuniones presenciales, virtuales y mentorías en un espacio amigable y seguro.



## <span style="color:#88398A"> ¿Por qué R-Ladies?</span> 

Nosotras estamos subrepresentadas en cada rol en la comunidad R:

1. desarrollo de paquetes
2. conferencistas invitadas
3. integrantes de comités
4. moderadoras
5. panelistas invitadas
6. dictado de tutoriales
7. posiciones de liderazgo en general

## <span style="color:#88398A"> Misión</span> 

Tener iniciativas con perspectiva de género permite incentivar que las minorías
de género participen más como oradoras, programadoras, líderes etc.


## <span style="color:#88398A">R-Ladies Global</span> 

https://gqueiroz.shinyapps.io/rshinylady/


## <span style="color:#88398A">R-Ladies Montevideo</span> 

- Empezamos: 2 Junio de 2017
- 118 miembros en meetup
- Primer meetup: 30 de Agosto de 2017

## <span style="color:#88398A">R-Ladies Montevideo Organizadoras</span>

- María Inés Fariello
- Paula Pereda
- Daniela Vazquez
- Natalia da Silva

## <span style="color:#88398A">R-Ladies Montevideo</span>

- Meetup: rladies.uy

- twitter: @RLadiesMVD

- facebook: RLadiesMVD 

- email:montevideo@rladies.org


## <span style="color:#88398A">R-Ladies Montevideo Planes</span>


- Investigación reproducible con `RMarkdown`. Paula Pereda

- Transformación de datos usando `dplyr`. Voluntaria/s?

- Control de versionado y trabajo colaborativo usando `git` y `GitHub` Voluntaria/s?

- Charlas #rstats. Voluntaria/s?

## <span style="color:#88398A">LatinR</span>

- Conferencia de usuarios de R para investigación y desarrollo
- Buenos Aires 4-5 Setiembre
- Oradores Plenarios Jenny Bryan y Walter Sosa
- Envios de trabajos 30 de Abril
- Web: latin-r.com  
- twitter: @LatinR2018


## <span style="color:#88398A">Invitadas</span>

- **Florencia Díaz Viraqué**: Lic.Bioquímica, Msc. en Ciencias Biológicas.
Actualmente estudiante de PhD en Biología molecular en @IPMontevideo.  

 Presenta: Código y paquetes para el análisis y visualización de secuencias biológicas en R


- **Fiorella Cavallieri**: Lic. Estadística y Economía, Docente FMED.  

Presenta: Modelos mixtos ¿ `nmle` o `lme4`?
